/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BardanaView {
  'plant' : string,
  'products' : Array<ProductView>,
}
export interface ChangeLog {
  'quantityChange' : bigint,
  'user' : string,
  'timestamp' : Time,
  'plant' : string,
  'product' : string,
}
export interface InventoryView {
  'plant' : string,
  'products' : Array<ProductView>,
}
export interface OrderView {
  'id' : bigint,
  'bags' : bigint,
  'date' : Time,
  'rate' : number,
  'brand' : string,
  'partyName' : string,
  'dalalName' : string,
  'remarks' : string,
}
export interface ProductView { 'name' : string, 'quantity' : number }
export interface RawMaterialView {
  'plant' : string,
  'products' : Array<ProductView>,
}
export type Time = bigint;
export interface ToolMachineryView {
  'quantity' : bigint,
  'remarks' : string,
  'product' : string,
}
export interface _SERVICE {
  'addInventoryStock' : ActorMethod<[string, string, bigint, string], boolean>,
  'addOrder' : ActorMethod<
    [Time, string, bigint, number, string, string, string],
    bigint
  >,
  'addToolMachinery' : ActorMethod<[string, bigint, string], undefined>,
  'deleteOrder' : ActorMethod<[bigint], undefined>,
  'deleteToolMachinery' : ActorMethod<[bigint], undefined>,
  'getBardana' : ActorMethod<[], Array<[string, BardanaView]>>,
  'getChangeLog' : ActorMethod<[], Array<[bigint, ChangeLog]>>,
  'getInventory' : ActorMethod<[], Array<[string, InventoryView]>>,
  'getOrders' : ActorMethod<[], Array<[bigint, OrderView]>>,
  'getRawMaterials' : ActorMethod<[], Array<[string, RawMaterialView]>>,
  'getSortedProductsByQuantity' : ActorMethod<
    [Array<ProductView>],
    Array<ProductView>
  >,
  'getToolsMachinery' : ActorMethod<[], Array<ToolMachineryView>>,
  'removeInventoryStock' : ActorMethod<
    [string, string, bigint, string],
    boolean
  >,
  'setBardanaStock' : ActorMethod<[string, string, number], boolean>,
  'setRawMaterialStock' : ActorMethod<[string, string, number], boolean>,
  'updateOrder' : ActorMethod<
    [bigint, Time, bigint, number, string, string, string],
    boolean
  >,
  'updateToolMachinery' : ActorMethod<[bigint, bigint, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];