/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ProductView = IDL.Record({
  'name' : IDL.Text,
  'quantity' : IDL.Float64,
});
export const BardanaView = IDL.Record({
  'plant' : IDL.Text,
  'products' : IDL.Vec(ProductView),
});
export const ChangeLog = IDL.Record({
  'quantityChange' : IDL.Int,
  'user' : IDL.Text,
  'timestamp' : Time,
  'plant' : IDL.Text,
  'product' : IDL.Text,
});
export const InventoryView = IDL.Record({
  'plant' : IDL.Text,
  'products' : IDL.Vec(ProductView),
});
export const OrderView = IDL.Record({
  'id' : IDL.Nat,
  'bags' : IDL.Int,
  'date' : Time,
  'rate' : IDL.Float64,
  'brand' : IDL.Text,
  'partyName' : IDL.Text,
  'dalalName' : IDL.Text,
  'remarks' : IDL.Text,
});
export const RawMaterialView = IDL.Record({
  'plant' : IDL.Text,
  'products' : IDL.Vec(ProductView),
});
export const ToolMachineryView = IDL.Record({
  'quantity' : IDL.Int,
  'remarks' : IDL.Text,
  'product' : IDL.Text,
});

export const idlService = IDL.Service({
  'addInventoryStock' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'addOrder' : IDL.Func(
      [Time, IDL.Text, IDL.Int, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addToolMachinery' : IDL.Func([IDL.Text, IDL.Int, IDL.Text], [], []),
  'deleteOrder' : IDL.Func([IDL.Nat], [], []),
  'deleteToolMachinery' : IDL.Func([IDL.Nat], [], []),
  'getBardana' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, BardanaView))],
      ['query'],
    ),
  'getChangeLog' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, ChangeLog))],
      ['query'],
    ),
  'getInventory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, InventoryView))],
      ['query'],
    ),
  'getOrders' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, OrderView))],
      ['query'],
    ),
  'getRawMaterials' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, RawMaterialView))],
      ['query'],
    ),
  'getSortedProductsByQuantity' : IDL.Func(
      [IDL.Vec(ProductView)],
      [IDL.Vec(ProductView)],
      ['query'],
    ),
  'getToolsMachinery' : IDL.Func([], [IDL.Vec(ToolMachineryView)], ['query']),
  'removeInventoryStock' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'setBardanaStock' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Bool],
      [],
    ),
  'setRawMaterialStock' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Bool],
      [],
    ),
  'updateOrder' : IDL.Func(
      [IDL.Nat, Time, IDL.Int, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateToolMachinery' : IDL.Func(
      [IDL.Nat, IDL.Int, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ProductView = IDL.Record({
    'name' : IDL.Text,
    'quantity' : IDL.Float64,
  });
  const BardanaView = IDL.Record({
    'plant' : IDL.Text,
    'products' : IDL.Vec(ProductView),
  });
  const ChangeLog = IDL.Record({
    'quantityChange' : IDL.Int,
    'user' : IDL.Text,
    'timestamp' : Time,
    'plant' : IDL.Text,
    'product' : IDL.Text,
  });
  const InventoryView = IDL.Record({
    'plant' : IDL.Text,
    'products' : IDL.Vec(ProductView),
  });
  const OrderView = IDL.Record({
    'id' : IDL.Nat,
    'bags' : IDL.Int,
    'date' : Time,
    'rate' : IDL.Float64,
    'brand' : IDL.Text,
    'partyName' : IDL.Text,
    'dalalName' : IDL.Text,
    'remarks' : IDL.Text,
  });
  const RawMaterialView = IDL.Record({
    'plant' : IDL.Text,
    'products' : IDL.Vec(ProductView),
  });
  const ToolMachineryView = IDL.Record({
    'quantity' : IDL.Int,
    'remarks' : IDL.Text,
    'product' : IDL.Text,
  });
  
  return IDL.Service({
    'addInventoryStock' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'addOrder' : IDL.Func(
        [Time, IDL.Text, IDL.Int, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addToolMachinery' : IDL.Func([IDL.Text, IDL.Int, IDL.Text], [], []),
    'deleteOrder' : IDL.Func([IDL.Nat], [], []),
    'deleteToolMachinery' : IDL.Func([IDL.Nat], [], []),
    'getBardana' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, BardanaView))],
        ['query'],
      ),
    'getChangeLog' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, ChangeLog))],
        ['query'],
      ),
    'getInventory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, InventoryView))],
        ['query'],
      ),
    'getOrders' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, OrderView))],
        ['query'],
      ),
    'getRawMaterials' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, RawMaterialView))],
        ['query'],
      ),
    'getSortedProductsByQuantity' : IDL.Func(
        [IDL.Vec(ProductView)],
        [IDL.Vec(ProductView)],
        ['query'],
      ),
    'getToolsMachinery' : IDL.Func([], [IDL.Vec(ToolMachineryView)], ['query']),
    'removeInventoryStock' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'setBardanaStock' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Bool],
        [],
      ),
    'setRawMaterialStock' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Bool],
        [],
      ),
    'updateOrder' : IDL.Func(
        [IDL.Nat, Time, IDL.Int, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateToolMachinery' : IDL.Func(
        [IDL.Nat, IDL.Int, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };