/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface ToolMachineryView {
    quantity: bigint;
    remarks: string;
    product: string;
}
export interface ProductView {
    name: string;
    quantity: number;
}
export interface ChangeLog {
    quantityChange: bigint;
    user: string;
    timestamp: Time;
    plant: string;
    product: string;
}
export interface InventoryView {
    plant: string;
    products: Array<ProductView>;
}
export interface BardanaView {
    plant: string;
    products: Array<ProductView>;
}
export interface RawMaterialView {
    plant: string;
    products: Array<ProductView>;
}
export interface OrderView {
    id: bigint;
    bags: bigint;
    date: Time;
    rate: number;
    brand: string;
    partyName: string;
    dalalName: string;
    remarks: string;
}
export interface backendInterface {
    addOrder(date: Time, brand: string, bags: bigint, rate: number, partyName: string, dalalName: string, remarks: string): Promise<bigint>;
    addToolMachinery(product: string, quantity: bigint, remarks: string): Promise<void>;
    deleteOrder(orderId: bigint): Promise<void>;
    deleteToolMachinery(index: bigint): Promise<void>;
    getBardana(): Promise<Array<[string, BardanaView]>>;
    getChangeLog(): Promise<Array<[bigint, ChangeLog]>>;
    getInventory(): Promise<Array<[string, InventoryView]>>;
    getOrders(): Promise<Array<[bigint, OrderView]>>;
    getRawMaterials(): Promise<Array<[string, RawMaterialView]>>;
    getSortedProductsByQuantity(products: Array<ProductView>): Promise<Array<ProductView>>;
    getToolsMachinery(): Promise<Array<ToolMachineryView>>;
    setBardanaStock(plant: string, productName: string, quantity: number): Promise<boolean>;
    setRawMaterialStock(plant: string, productName: string, quantity: number): Promise<boolean>;
    setStock(plant: string, productName: string, quantity: number, user: string): Promise<boolean>;
    updateOrder(orderId: bigint, date: Time, bags: bigint, rate: number, partyName: string, dalalName: string, remarks: string): Promise<boolean>;
    updateToolMachinery(index: bigint, quantity: bigint, remarks: string): Promise<boolean>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addOrder(arg0: Time, arg1: string, arg2: bigint, arg3: number, arg4: string, arg5: string, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrder(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrder(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addToolMachinery(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToolMachinery(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToolMachinery(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteOrder(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOrder(arg0);
            return result;
        }
    }
    async deleteToolMachinery(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteToolMachinery(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteToolMachinery(arg0);
            return result;
        }
    }
    async getBardana(): Promise<Array<[string, BardanaView]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBardana();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBardana();
            return result;
        }
    }
    async getChangeLog(): Promise<Array<[bigint, ChangeLog]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChangeLog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChangeLog();
            return result;
        }
    }
    async getInventory(): Promise<Array<[string, InventoryView]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventory();
            return result;
        }
    }
    async getOrders(): Promise<Array<[bigint, OrderView]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders();
            return result;
        }
    }
    async getRawMaterials(): Promise<Array<[string, RawMaterialView]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRawMaterials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRawMaterials();
            return result;
        }
    }
    async getSortedProductsByQuantity(arg0: Array<ProductView>): Promise<Array<ProductView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSortedProductsByQuantity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSortedProductsByQuantity(arg0);
            return result;
        }
    }
    async getToolsMachinery(): Promise<Array<ToolMachineryView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getToolsMachinery();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getToolsMachinery();
            return result;
        }
    }
    async setBardanaStock(arg0: string, arg1: string, arg2: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setBardanaStock(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBardanaStock(arg0, arg1, arg2);
            return result;
        }
    }
    async setRawMaterialStock(arg0: string, arg1: string, arg2: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setRawMaterialStock(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRawMaterialStock(arg0, arg1, arg2);
            return result;
        }
    }
    async setStock(arg0: string, arg1: string, arg2: number, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setStock(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStock(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateOrder(arg0: bigint, arg1: Time, arg2: bigint, arg3: number, arg4: string, arg5: string, arg6: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrder(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrder(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateToolMachinery(arg0: bigint, arg1: bigint, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateToolMachinery(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateToolMachinery(arg0, arg1, arg2);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
